### PR TITLE
Homebrew Formula Metadata

### LINKED ISSUE #87: Homebrew Environmental Var
Looks like this commit got merged in and is now causing issues with the `homebrew_package` library.

The brew bash script now populates environmental variables which the config library is dependent upon.

https://github.com/Homebrew/homebrew/commit/390e327f55126f7ee9519bc6c03a0c0aa14f7168

```
Recipe: homebrew::install_formulas
  * homebrew_package[homebrew/php/composer] action install

    ================================================================================
    Error executing action `install` on resource 'homebrew_package[homebrew/php/composer]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of nil into String

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:94:in `version_from_formula'
    /var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:74:in `current_installed_version'
    /var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:44:in `load_current_resource'
```

Something like the following needs to be added to the `homebrew_package` library

```
  ENV['HOMEBREW_PREFIX'] = brew_cmd.stdout.chomp
  ENV['HOMEBREW_REPOSITORY'] = ENV['HOMEBREW_PREFIX']
  ENV['HOMEBREW_LIBRARY'] = ::File.join(ENV['HOMEBREW_REPOSITORY'], 'Library')
  ENV['HOMEBREW_CELLAR'] = ::File.join(ENV['HOMEBREW_PREFIX'], 'Cellar')
```

### PR DESCRIPTION
**Pull request by bdwyertech**
- Use the officially supported method of querying Homebrew data, rather than tying directly into it's code
- Fixes #87

### CODE REVIEW

**Comment by bdwyertech** [comment]
See https://github.com/Homebrew/homebrew/pull/48261
```
FWIW the supported way to access formula metadata is with the JSON output; see e.g. brew info --all --json=v1, which provides the attributes you want.
Yup, this. Our internal Ruby code is not an API you can rely on remaining static.
```

**Comment by dougireton** [comment]
Thanks for the quick PR. This will get our `chefdk_bootstrap` cookbook working again for Mac users. :rocket:

**Comment by jeroenj** [comment]
Nice. Thanks! :+1:

**Comment by mikemcquaid** [comment]
Great work, thanks.

**Pull request merged**
